name: Create Release

on:
  push:
    tags:
      - 'v*' # Dispara quando um tag que começa com "v" é criado (ex: v1.0.0)

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Ajuste para a versão do PHP usada no projeto

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Generate Release Notes
        id: generate_release_notes
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const tagName = context.ref.replace('refs/tags/', '');
            const changelog = require('fs').readFileSync('CHANGELOG.md', 'utf8');
            return {
              tag_name: tagName,
              name: `Release ${tagName}`,
              body: changelog,
              draft: false,
              prerelease: false
            };

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.generate_release_notes.outputs.tag_name }}
          release_name: ${{ steps.generate_release_notes.outputs.name }}
          body: ${{ steps.generate_release_notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}